backend:
  name: github
  repo: aherisystems-cloud/wgd-blog
  branch: main
  client_id: Ov23litbfWQD8obeUprf

media_folder: "content/images"
public_folder: "/content/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

